jeap:
  security:
    oauth2:
      resourceserver:
        authorization-server:
          issuer: "https://keycloak-ref.nivel.bazg.admin.ch/realms/bit-jme"
          jwk-set-uri: "https://internal.keycloak-ref.nivel.bazg.admin.ch/realms/bit-jme/protocol/openid-connect/certs"
  swagger:
    status: OPEN
  web:
    tls:
      enabled: true

frontend:
  auth:
    authority: ${jeap.security.oauth2.resourceserver.authorization-server.issuer}
    applicationUrl: https://jme-ref.ingress.nivel.bazg.admin.ch${server.servlet.context-path}/
    logoutRedirectUri: https://eportal-r.admin.ch
    mockPams: false
    pamsEnvironment: REF
    tokenAwarePatterns:
      - "^${server.servlet.context-path}/api/.*"
    clientId: jme-server-sent-events-scs
