spring:
  application:
    name: jme-server-sent-events-scs
  jpa:
    open-in-view: false

server:
  port: 8080
  servlet:
    context-path: /${spring.application.name}
  compression:
    enabled: true

# Set a default client-ID to use
springdoc:
  swagger-ui:
    oauth:
      client-id: microService
    try-it-out-enabled: true

jeap:
  security:
    oauth2:
      resourceserver:
        system-name: "jme"
  swagger:
    status: OPEN
  web:
    headers:
      content-security-policy: "default-src 'self' localhost:* *.admin.ch data:; script-src 'self' 'unsafe-inline' *.admin.ch; style-src 'self' 'unsafe-inline'; frame-src 'self' *.admin.ch;"
    tls:
      enabled: false
  sse:
    kafka:
      topic: jme-server-sent-events-scs-notifyclient
    web:
      insecure:
        enabled: true
  messaging:
    kafka:
      systemName: jme
      errorTopicName: jme-messageprocessing-failed

frontend:
  auth:
    pamsAppId: "notSet"
    auto-login: true
    silent-renew: true
    system-name: ${jeap.security.oauth2.resourceserver.system-name}
    renew-user-info-after-token-renew: true

