server:
  port: 8081

jeap:
  security:
    oauth2:
      resourceserver:
        authorization-server:
          issuer: "http://localhost:8082/default-oauth-mock-server"
          jwk-set-uri: "${jeap.security.oauth2.resourceserver.authorization-server.issuer}/.well-known/jwks.json"
  swagger:
    status: OPEN
  monitor:
    prometheus:
      password: "{noop}secret"
  messaging:
    kafka:
      systemName: jme
      errorTopicName: errorTopic
      message-type-encryption-disabled: true
      bootstrapServers: "http://localhost:9092"
      schemaRegistryUrl: "http://localhost:7781"
      username: user
      password: user-secret
      securityProtocol: SASL_PLAINTEXT
      set-compatibility-mode-none: true

#Store the client secret plain text for dev like environments
springdoc:
  swagger-ui:
    oauth:
      client-secret: secret

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    url: "jdbc:postgresql://localhost:5433/sample-secure-example-db"
    username: db-user
    password: db-pass
    hikari:
      schema: data

frontend:
  auth:
    authority: ${jeap.security.oauth2.resourceserver.authorization-server.issuer}
    applicationUrl: http://localhost:8081${server.servlet.context-path}/
    logoutRedirectUri: http://localhost:4199/
    mockPams: true
    pamsEnvironment: DEV
    tokenAwarePatterns:
      - "^${server.servlet.context-path}/api/.*" # build-prod
      - "^${frontend.auth.applicationUrl}api/.*" # build-dev
    clientId: microService
