server:
  port: 8082
  servlet:
    context-path: "/default-oauth-mock-server"

mockserver:
  base-url: "http://localhost:${server.port}${server.servlet.context-path}"

jeap:
  monitor:
    prometheus:
      user: "prometheus"
      password: "{noop}secret"
  web:
    tls:
      enabled: false
