base-url: "https://bit-jme-d.apps.p-szb-ros-shrd-npr-01.cloud.admin.ch"

mockserver:
  base-url: "${base-url}/${spring.application.name}"

management:
  server:
    port: 8082
    base-path: /${spring.application.name}

jeap:
  monitor:
    prometheus:
      secure: false
  web:
    tls:
      enabled: false
